// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/components/functionCard":{"path":"components/function-card","id":"docs/components/functionCard","parentId":"DocLayout"},"docs/guide/installation":{"path":"guide/installation","id":"docs/guide/installation","parentId":"DocLayout"},"docs/components/button":{"path":"components/button","id":"docs/components/button","parentId":"DocLayout"},"docs/components/toast":{"path":"components/toast","id":"docs/components/toast","parentId":"DocLayout"},"docs/components/icon":{"path":"components/icon","id":"docs/components/icon","parentId":"DocLayout"},"docs/guide/index":{"path":"guide","id":"docs/guide/index","parentId":"DocLayout"},"docs/guide/theme":{"path":"guide/theme","id":"docs/guide/theme","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/zhangqi/Desktop/pos-ui/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.4_@swc+helpers@0.5.15_@types+node@24.7.1_@types+react@19.2_b4da66a71792359bcf860565c42aee78/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/zhangqi/Desktop/pos-ui/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/zhangqi/Desktop/pos-ui/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.4_@swc+helpers@0.5.15_@types+node@24.7.1_@types+react@19.2_b4da66a71792359bcf860565c42aee78/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/components/functionCard': React.lazy(() => import(/* webpackChunkName: "docs__components__functionCard.md" */'/Users/zhangqi/Desktop/pos-ui/docs/components/functionCard.md')),
'docs/guide/installation': React.lazy(() => import(/* webpackChunkName: "docs__guide__installation.md" */'/Users/zhangqi/Desktop/pos-ui/docs/guide/installation.md')),
'docs/components/button': React.lazy(() => import(/* webpackChunkName: "docs__components__button.md" */'/Users/zhangqi/Desktop/pos-ui/docs/components/button.md')),
'docs/components/toast': React.lazy(() => import(/* webpackChunkName: "docs__components__toast.md" */'/Users/zhangqi/Desktop/pos-ui/docs/components/toast.md')),
'docs/components/icon': React.lazy(() => import(/* webpackChunkName: "docs__components__icon.md" */'/Users/zhangqi/Desktop/pos-ui/docs/components/icon.md')),
'docs/guide/index': React.lazy(() => import(/* webpackChunkName: "docs__guide__index.md" */'/Users/zhangqi/Desktop/pos-ui/docs/guide/index.md')),
'docs/guide/theme': React.lazy(() => import(/* webpackChunkName: "docs__guide__theme.md" */'/Users/zhangqi/Desktop/pos-ui/docs/guide/theme.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/zhangqi/Desktop/pos-ui/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/zhangqi/Desktop/pos-ui/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.4_@swc+helpers@0.5.15_@types+node@24.7.1_@types+react@19.2_b4da66a71792359bcf860565c42aee78/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
