// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/zhangqi/Desktop/pos-ui/docs/components/functionCard.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/zhangqi/Desktop/pos-ui/docs/components/functionCard.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/zhangqi/Desktop/pos-ui/docs/guide/installation.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/zhangqi/Desktop/pos-ui/docs/guide/installation.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/zhangqi/Desktop/pos-ui/docs/components/button.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/zhangqi/Desktop/pos-ui/docs/components/button.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/zhangqi/Desktop/pos-ui/docs/components/toast.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/zhangqi/Desktop/pos-ui/docs/components/toast.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/zhangqi/Desktop/pos-ui/docs/components/icon.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/zhangqi/Desktop/pos-ui/docs/components/icon.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/zhangqi/Desktop/pos-ui/docs/guide/index.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/zhangqi/Desktop/pos-ui/docs/guide/index.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/zhangqi/Desktop/pos-ui/docs/guide/theme.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/zhangqi/Desktop/pos-ui/docs/guide/theme.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/zhangqi/Desktop/pos-ui/docs/index.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/zhangqi/Desktop/pos-ui/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/components/functionCard': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangqi/Desktop/pos-ui/docs/components/functionCard.md?type=text'),
  },
  'docs/guide/installation': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangqi/Desktop/pos-ui/docs/guide/installation.md?type=text'),
  },
  'docs/components/button': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangqi/Desktop/pos-ui/docs/components/button.md?type=text'),
  },
  'docs/components/toast': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangqi/Desktop/pos-ui/docs/components/toast.md?type=text'),
  },
  'docs/components/icon': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangqi/Desktop/pos-ui/docs/components/icon.md?type=text'),
  },
  'docs/guide/index': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangqi/Desktop/pos-ui/docs/guide/index.md?type=text'),
  },
  'docs/guide/theme': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangqi/Desktop/pos-ui/docs/guide/theme.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhangqi/Desktop/pos-ui/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
