export { default as SuccessIcon } from './success';
export { default as ErrorIcon } from './error';
export { default as WarningIcon } from './warning';
export { default as InfoIcon } from './info';
export { default as CloseIcon } from './close';
export { default as DarkIcon } from './dark';
export { default as LightIcon } from './light';

export { default as AdminIcon } from './admin';
export { default as BatchIcon } from './batch';
export { default as DeliveryIcon } from './delivery';
export { default as DineInIcon } from './dineIn';
export { default as DrawerIcon } from './drawer';
export { default as PickupIcon } from './pickup';
export { default as RecallIcon } from './recall';
export { default as ReportIcon } from './report';
export { default as RoleIcon } from './role';
export { default as TogoIcon } from './togo';
export { default as DefaultMenuIcon } from './defaultMenu';
