// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhangqi/Desktop/pos-ui/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.4_@swc+helpers@0.5.15_@types+node@24.7.1_@types+react@19.2_b4da66a71792359bcf860565c42aee78/node_modules/dumi/theme-default/slots/Header/index.js';
